name: Bug
description: Report an issue to help improve the project.
title: "[BUG] <description>"
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of the bug you have found. Please include relevant information and resources (for example the steps to reproduce the bug)
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Please add screenshots if applicable
    validations:
      required: false