blank_issues_enabled: false
contact_links:
  - name: Question?
    url: https://github.com/at-the-vr/convelations/discussions
    about: Any form of Query can be actively discussed in GitHub Discussions